// --------------------------------------------------------------------------------------------------------------------
// <copyright file="UriExtensions.cs" company="OBeautifulCode">
//   Copyright (c) OBeautifulCode 2018. All rights reserved.
// </copyright>
// <auto-generated>
//   Sourced from NuGet package. Will be overwritten with package update except in OBeautifulCode.Uri.Recipes source.
// </auto-generated>
// --------------------------------------------------------------------------------------------------------------------

namespace OBeautifulCode.Uri.Recipes
{
    /// <summary>
    /// Extension methods on <see cref="System.Uri"/>.
    /// </summary>
#if !OBeautifulCodeUriSolution
    [global::System.Diagnostics.CodeAnalysis.ExcludeFromCodeCoverage]
    [global::System.CodeDom.Compiler.GeneratedCode("OBeautifulCode.Uri.Recipes", "See package version number")]
    internal
#else
    public
#endif
    class UriExtensions
    {
    }
}